// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Database } from '@/types/database.types';

// Default values for development
const DEFAULT_SUPABASE_URL = 'https://ulqlhjluytobqaviuswk.supabase.co';
const DEFAULT_SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVscWxoamx1eXRvYnFhdml1c3drIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNDQ0MDcsImV4cCI6MjA2MjYyMDQwN30.wbslqPS_NHHvUr5GDXpSJI6ey4nXH1HWfFJxxWsK3TY';

// Get environment variables with fallbacks
const envSupabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const envSupabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Use default values if environment variables are empty strings or undefined
const supabaseUrl = envSupabaseUrl && envSupabaseUrl !== '' ? envSupabaseUrl : DEFAULT_SUPABASE_URL;
const supabaseAnonKey = envSupabaseAnonKey && envSupabaseAnonKey !== '' ? envSupabaseAnonKey : DEFAULT_SUPABASE_ANON_KEY;

// Log environment status (only in development)
if (import.meta.env.DEV) {
  console.log('Environment Status:', {
    hasSupabaseUrl: !!envSupabaseUrl && envSupabaseUrl !== '',
    hasSupabaseAnonKey: !!envSupabaseAnonKey && envSupabaseAnonKey !== '',
    usingDefaultUrl: !envSupabaseUrl || envSupabaseUrl === '',
    usingDefaultKey: !envSupabaseAnonKey || envSupabaseAnonKey === '',
    actualUrl: supabaseUrl,
    actualKeyFirstChars: supabaseAnonKey.substring(0, 10) + '...'
  });
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    storageKey: 'exhibae-connect-auth'
  },
  realtime: {
    params: {
      eventsPerSecond: 10
    }
  },
  global: {
    headers: {
      'X-Client-Info': 'exhibae-connect@1.0.0'
    }
  },
  db: {
    schema: 'public'
  },
  storage: {
    retryAttempts: 3,
    multipartThreshold: 5242880, // 5MB
    maxRetryDelay: 5000
  }
});