name: Deploy to Production

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          eval $(ssh-agent -s)
          
          # Debug key content
          echo "Key file permissions:"
          ls -la ~/.ssh/deploy_key
          
          echo "Key file content format:"
          head -n 1 ~/.ssh/deploy_key
          
          # Add key to agent
          ssh-add ~/.ssh/deploy_key
          
          # Add server to known hosts
          ssh-keyscan -H 69.62.77.142 >> ~/.ssh/known_hosts
          
          # Test connection
          ssh -v -o StrictHostKeyChecking=no deployer@69.62.77.142 "echo 'SSH connection test successful'"
          
      - name: Deploy to server
        env:
          DEPLOY_PATH: /var/www/exhibae
        run: |
          echo "Starting deployment process..."
          
          # Create deploy directory
          mkdir -p deploy
          
          # Debug directory contents
          echo "Checking build files..."
          ls -la dist/
          
          # Copy build files
          cp -r dist/* deploy/
          cp .htaccess deploy/ || echo "No .htaccess file found"
          cp .env.production deploy/.env || echo "No .env.production file found"
          
          echo "Checking deployment files..."
          ls -la deploy/
          
          # Create backup of current deployment
          echo "Creating backup..."
          ssh deployer@69.62.77.142 "if [ -d $DEPLOY_PATH ]; then cp -r $DEPLOY_PATH ${DEPLOY_PATH}_backup_$(date +%Y%m%d_%H%M%S); fi"
          
          # Deploy using rsync with progress
          echo "Deploying files..."
          rsync -avz --progress --delete deploy/ deployer@69.62.77.142:$DEPLOY_PATH
          
          # Set proper permissions
          echo "Setting permissions..."
          ssh deployer@69.62.77.142 "sudo chown -R www-data:www-data $DEPLOY_PATH && sudo chmod -R 755 $DEPLOY_PATH"
          
          # Verify deployment
          echo "Verifying deployment..."
          ssh deployer@69.62.77.142 "ls -la $DEPLOY_PATH"
          
          # Cleanup local
          rm -rf deploy 