name: Deploy to Production

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H 69.62.77.142 >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          # Create deployment package
          cd dist
          tar czf ../deploy.tar.gz .
          cd ..

          # Upload to server
          scp -i ~/.ssh/deploy_key deploy.tar.gz root@69.62.77.142:/tmp/

          # Execute deployment commands
          ssh -i ~/.ssh/deploy_key root@69.62.77.142 "
            set -e
            cd /tmp
            
            # Backup current deployment
            TIMESTAMP=\$(date +%Y%m%d_%H%M%S)
            if [ -d /var/www/exhibae ]; then
              mkdir -p /var/www/exhibae_backups
              cp -r /var/www/exhibae /var/www/exhibae_backups/backup_\${TIMESTAMP}
            fi

            # Preserve existing .env if it exists
            if [ -f /var/www/exhibae/.env ]; then
              cp /var/www/exhibae/.env /tmp/env.temp
            fi

            # Extract new files
            rm -rf /var/www/exhibae/*
            cd /var/www/exhibae
            tar xzf /tmp/deploy.tar.gz

            # Restore .env if it was preserved
            if [ -f /tmp/env.temp ]; then
              mv /tmp/env.temp .env
            fi

            # Set proper permissions
            chown -R www-data:www-data .
            find . -type d -exec chmod 755 {} \;
            find . -type f -exec chmod 644 {} \;
            chmod -R g+w assets 2>/dev/null || true

            # Cleanup
            rm -f /tmp/deploy.tar.gz

            # Cleanup old backups (keep last 5)
            cd /var/www/exhibae_backups
            ls -t | tail -n +6 | xargs -r rm -rf

            echo 'Deployment completed successfully!'
          " 